spring:
  batch:
    job:
      names: ${job.name:NONE}
    initialize-schema:
  datasource:
    driver-class-name: org.h2.Driver # Spring boot는 이 값을 기준으로 DataSource 를 자동으로 생성 해준다. 그렇기에 생성자로 DataSource 를 자동으로 주입 받을 수 있다.
#    data: classpath:person.sql  # resource 디렉토리의 person.sql을 자동 실행한다.

# spring.vatch.job.names 라는 설정 값을 job.name 으로 커스터마이징, 이렇게 작성해주면 application 실행 시 모든 Job 을 실행하지 않아 Application 실행하면서 자동으로 실행되는 것을 막을 수 있다.

# Script 생성 시점 설정
#   initialize-schema: always, embedded, never
#     always : mysql 같은 DB에서 사용 (개발 환경에서)
#     embedded : h2 DB와 같은 내장 DB 에서 사용 (개발 환경에서) - default
#     never : 어떤 환경에서도 실행하지 않는 조건 (운영 환경에서 사용 -> script 를 직접 생성해서 관리하는 것을 추천)



